name: close issue

on:
  issues:
    types: [labeled]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.label.name == 'close'
        name: Close Issue
        uses: peter-evans/close-issue@v1